import {
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatButtonModule,
    MatCardModule,
    MatCheckboxModule,
    MatTabsModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatAutocompleteModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatToolbarModule,
    MatSelectModule,
    MatPaginatorModule,
    MatRadioModule,
    MatTableModule,
    MatSortModule,
    MatChipsModule,
    MatFormFieldModule,
    MatExpansionModule,
    MatTooltipModule,
    MatTreeModule,
    MatMenuModule,
    MatSlideToggleModule,
    MatButtonToggleModule,
    MatStepperModule,
    MatBadgeModule,
    MatProgressBarModule
  } from '@angular/material';

  import {
    OverlayModule
  } from '@angular/cdk/overlay';

  export const angularMaterialModule = [
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatButtonModule,
    MatCardModule,
    MatCheckboxModule,
    MatTabsModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatAutocompleteModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatToolbarModule,
    MatSelectModule,
    MatPaginatorModule,
    MatRadioModule,
    MatTableModule,
    MatSortModule,
    OverlayModule,
    MatChipsModule,
    MatFormFieldModule,
    MatExpansionModule,
    MatTooltipModule,
    MatMenuModule,
    MatTreeModule,
    MatSlideToggleModule,
    MatButtonToggleModule,
    MatStepperModule,
    MatBadgeModule,
    MatProgressBarModule
  ];
